### ISSUE TITLE
Dynamc child pipelines are not visible

### ISSUE THREAD

**Issue by kivipe** [heikkipora/gitlab-radiator#93]
I have a pipeline that runs a child job with trigger:influence:artifact. Radiator shows only triggering part of the pipeline and not triggered part.

**Comment by heikkipora** [comment]
Would you like to provide a small sample pipeline YML file that can be used to reproduce that situation?

**Comment by kivipe** [comment]
Hi, here are two files:

.gitlab-ci.yml:
```
stages:
   - start
   - run-child

start-job:
  stage: start
  script:
    - echo start stage

run-child:
  stage: run-child
  trigger:
    include:
      - .gitlab-child.yml
    strategy: depend
```

.gitlab-child.yml
```
stages:
  - build
  - test

build:
  stage: build
  script:
  - echo build stage

test:
  stage: test
  script:
  - echo test stage
```
